spring:
  application:
    name: keycloak-auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
          jwk-set-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}/protocol/openid-connect/certs
server:
  port: 8443

app:
  keycloak:
    admin:
      clientId: DN
      clientSecret: jwsWp8mjAPxLdA8jew4yTy8mmIzzKilu
      adminClientId: admin-cli
      adminClientSecret: PR3zwHqXHp0R8YB4WN86gkgtCvNRdEfZ
    realm: DirectNexus
    serverUrl: https://88.99.174.69:8443