spring:
  application:
    name: DirectNexus
  datasource:
    url: jdbc:postgresql://localhost:5432/direct_nexus
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
