spring:
  application:
    name: keycloak-auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
          jwk-set-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}/protocol/openid-connect/certs
server:
  port: 6700

app:
  keycloak:
    admin:
      clientId: DN
      clientSecret: mv500tThtNip1DFystTsF3vKrCA6cDW9
      adminClientId: admin-cli
      adminClientSecret: vwFAPRfDKTOLJcKMpO8B1l5eQEHh02dG
    realm: DirectNexus
    serverUrl: https://keycloak.boostergin.com