
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: direct_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: direct_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    links:
      - postgres
    ports:
      - "9082:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: direct_user
      KC_DB_PASSWORD: 1234
      KC_DB_URL: jdbc:postgresql://postgres:5432/direct_db
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz

    networks:
      - local

networks:
  local:

volumes:
  postgres_data:
